name: GitHub Releases Push
on:
  release:
    types:
      - created
  push:
#     branches:
#       - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to the ghcr.io 
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GHCR_TOKEN}}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/mcuadros/ofelia:${{ github.sha }}
        
#     - name: Build and push
#       uses: docker/build-push-action@v3
#       if: github.event_name == 'release'
#       with:
#         push: true
#         tags: mcuadros/ofelia:latest
